name: Benchmarks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install
           npm install bit-meddler
    - run: npm run build --if-present
    - run: node ./benchmark/bitcount.js
    - run: node ./benchmark/highestBit.js
    - run: node ./benchmark/offset.js
    - run: node ./benchmark/general.js
